[versions]
androidGradlePlugin = "8.13.0"
androidxCore = "1.16.0"
androidxActivity = "1.11.0"
androidxWebkit = "1.14.0"
androidxAppCompat = "1.7.1"
kotlin = "2.1.20"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidxWebkit" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }